### ISSUE TITLE
Error in updating member from bulk added members

### ISSUE THREAD

**Issue by hyperion21** [cristal-ise/cristal-ise#461] opened 2020-12-15 09:16 UTC
`MemberUpdateSchema` property is missing from the created member in bulk add member. And check if other properties is not also added. The error shows only the first property that is not found
```
org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Property MemberUpdateSchema does not exists for slotID:0
	at org.cristalise.kernel.collection.DependencyMember.updateProperties(DependencyMember.java:252)
	at org.cristalise.kernel.collection.Dependency.updateMember(Dependency.java:170)
	at org.cristalise.kernel.lifecycle.instance.predefined.UpdateDependencyMember.runActivityLogic(UpdateDependencyMember.java:83)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:243)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:195)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:134)
	at org.cristalise.kernel.entity.ItemImplementation.delegatedAction(ItemImplementation.java:190)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:154)
	at org.cristalise.kernel.entity.TraceableEntity.requestAction(TraceableEntity.java:128)
	at org.cristalise.kernel.entity.ItemPOA._invoke(ItemPOA.java:187)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:654)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:205)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1700)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:1558)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleInput(CorbaMessageMediatorImpl.java:940)
	at com.sun.corba.se.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:198)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:712)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.dispatch(SocketOrChannelConnectionImpl.java:474)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.doWork(SocketOrChannelConnectionImpl.java:1237)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:490)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)
```

**Comment by kovax** [comment] 2020-12-21 13:51
I do not think this is a bug.

The Script calling `AddMemberCollection` or `AddMembersCollection` has to send all Properties that the member shall contain. Only transitive properties defined in the collection will be coped automatically to member. Also `UpdateDependencyMember` can only update existing member properties.

**Comment by hyperion21** [comment] 2020-12-21 14:04
@kovax I see, there is no issue in server side, I think in the restapi, based on the structure of item-collection it also passed `MemberUpdateSchema` so I adjusted the properties need to be passed. And since we cant use UpdateDependencyMember via Viewpoint I also created an outcome with schema declaration to validate the job/schema

**Comment by kovax** [comment] 2020-12-22 12:38
We agreed that this is not a bug. The branch is merged because the collection test was improved significantly.

**Closed by kovax** 2020-12-22 12:38 UTC
Labels: kernel
