### ISSUE TITLE
ProxyManager log should be tuned in order to avoid overflow when testing

### ISSUE THREAD

**Issue by martinbielmannicube** [cristal-ise/cristal-ise#336] opened 2020-01-29 08:56 UTC
Proxy manager generates the following log: 
`o.c.kernel.entity.proxy.ProxyManager - Received proxy message for sysKey /entity/f91c29e0-f8d7-45d2-8c08-ce0094517a25 which we don't have a proxy for.`
Under testing, if items are erased, this log is generated about 30 times for each sysKey. 
The purpose of this issue ticket is to check the number of occurrences of the log per sysKey, or to lower its level to "INFO".

**Comment by kovax** [comment] 2020-04-14 13:21
This warn is happens a lot in test envs, because Item are deleted regularly. So keeping the warn level, because it could help to investigate issue in production.

**Comment by kovax** [comment] 2020-04-14 13:31
The issue is merged, because lot of log message were improved

**Closed by kovax** 2020-04-14 13:31 UTC
Labels: bug, kernel
